name: Brain Dump
description: Tech Brain-dump
meta_description: "Techy things I might be glad I wrote down one day."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mehcoleman.com'
google_analytics: 'UA-65564199-1'

# Details for the RSS feed generator
url:            'http://mehcoleman.com'
author:         'Mark Coleman'
